name: ci

on:
  pull_request:
  push:
    branches:
    - main
  workflow_call:
    inputs:
      release:
        description: Whether this is running as part of a release workflow.
        required: false
        type: boolean
        default: false
      version:
        description: The version tag.
        required: false
        type: string
        default: '0.1.0'

jobs:
  test:
    runs-on: windows-latest
    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v3

    # Test
    - name: Set up toolchain
      run: rustup show
    - name: Check formatting
      if: ${{ success() && (!inputs.release || github.event_name != 'workflow_call') }}
      run: cargo fmt --all -- --check
    - name: Test
      run: cargo test --release --all-features --workspace
      env:
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: -Dwarnings
    - name: Lint
      run: cargo clippy --all-features --all-targets --no-deps --workspace

    # Package
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Set version
      run: |
        if ('${{ inputs.version }}') {
          $version = '${{ inputs.version }}' -replace '^v', ''
          Write-Host "Setting version '$version'"
          "version=$version" >> $env:GITHUB_OUTPUT
        } else {
          'version=0.1.0' >> $env:GITHUB_OUTPUT
        }
      id: set-version
      shell: pwsh
    - name: Build
      run: cargo build --release
      env:
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: -Dwarnings
    - name: Build WiX extension
      run: msbuild .\build\wix\extension.wixproj -p:Configuration=Release -v:detailed
    - name: Build NuGet package
      run: nuget pack .\build\wix\extension.nuspec -Version "${{ steps.set-version.outputs.version }}" -OutputDirectory .\target\release
    - name: Upload extension
      uses: actions/upload-artifact@v3
      with:
        path: target/release/*.nupkg
