name: release

on:
  push:
    tags:
    - "v*"

permissions:
  contents: write
  packages: write

jobs:
  test:
    uses: ./.github/workflows/ci.yml
    with:
      release: true
      version: ${{ github.ref_name }}

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Download extension
      uses: actions/download-artifact@v3
      id: download-artifact
    - name: Publish extension
      run: |
        $nupkg = dir '${{ steps.download-artifact.outputs.download-path }}' -filter *.nupkg -recurse | select-object -first 1
        Write-Host "Publishing '$nupkg'"
        nuget push "$nupkg" -Source "https://nuget.pkg.github.com/heaths/index.json" -ApiKey "${env:GITHUB_TOKEN}" -NoSymbols -Verbosity detailed
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Release
      run: gh release create ${{ github.ref_name }} --generate-notes
      env:
        GH_TOKEN: ${{ github.token }}
